/*
 Rangy, a cross-browser JavaScript range and selection library
 http://code.google.com/p/rangy/

 Copyright 2010, Tim Down
 Licensed under the MIT license.
 Version: 1.0b2
 Build date: 21 November 2010
*/
var rangy=function(){function p(n,r){var x=typeof n[r];return x=="function"||!!(x=="object"&&n[r])||x=="unknown"}function E(n,r){return!!(typeof n[r]=="object"&&n[r])}function F(n,r){return typeof n[r]!="undefined"}function w(n){return function(r,x){for(var M=x.length;M--;)if(!n(r,x[M]))return false;return true}}function A(n){window.alert("Rangy not supported in your browser. Reason: "+n);s.initialized=true;s.supported=false}function H(){if(!s.initialized){var n,r=false,x=false;if(p(document,"createRange")){n=
document.createRange();if(v(n,j)&&t(n,N))r=true;n.detach()}if((n=E(document,"body")?document.body:document.getElementsByTagName("body")[0])&&p(n,"createTextRange")){n=n.createTextRange();if(v(n,m)&&t(n,l))x=true}!r&&!x&&A("Neither Range nor TextRange are implemented");s.initialized=true;s.features={implementsDomRange:r,implementsTextRange:x};r=d.concat(e);x=0;for(n=r.length;x<n;++x)try{r[x](s)}catch(M){E(window,"console")&&p(window.console,"log")&&console.log("Init listener threw an exception. Continuing.",
M)}}}function G(n){this.name=n;this.supported=this.initialized=false}var N=["startContainer","startOffset","endContainer","endOffset","collapsed","commonAncestorContainer","START_TO_START","START_TO_END","END_TO_START","END_TO_END"],j=["setStart","setStartBefore","setStartAfter","setEnd","setEndBefore","setEndAfter","collapse","selectNode","selectNodeContents","compareBoundaryPoints","deleteContents","extractContents","cloneContents","insertNode","surroundContents","cloneRange","toString","detach"],
l=["boundingHeight","boundingLeft","boundingTop","boundingWidth","htmlText","text"],m=["collapse","compareEndPoints","duplicate","getBookmark","moveToBookmark","moveToElementText","parentElement","pasteHTML","select","setEndPoint"],v=w(p),y=w(E),t=w(F),s={initialized:false,supported:true,util:{isHostMethod:p,isHostObject:E,isHostProperty:F,areHostMethods:v,areHostObjects:y,areHostProperties:t},features:{},modules:{},config:{alertOnWarn:false}};s.fail=A;s.warn=function(n){n="Rangy warning: "+n;if(s.config.alertOnWarn)window.alert(n);
else typeof window.console!="undefined"&&typeof window.console.log!="undefined"&&window.console.log(n)};s.init=H;var e=[],d=[];s.addInitListener=function(n){s.initialized?n(s):e.push(n)};var i=[];s.addCreateMissingNativeApiListener=function(n){i.push(n)};s.createMissingNativeApi=function(n){n=n||window;H();for(var r=0,x=i.length;r<x;++r)i[r](n)};G.prototype.fail=function(n){this.initialized=true;this.supported=false;throw Error("Module '"+this.name+"' failed to load: "+n);};G.prototype.createError=
function(n){return Error("Error in Rangy "+this.name+" module: "+n)};s.createModule=function(n,r){var x=new G(n);s.modules[n]=x;d.push(function(M){r(M,x);x.initialized=true;x.supported=true})};s.requireModules=function(n){for(var r=0,x=n.length,M,R;r<x;++r){R=n[r];M=s.modules[R];if(!M||!(M instanceof G))throw Error("Module '"+R+"' not found");if(!M.supported)throw Error("Module '"+R+"' not supported");}};var q=false;y=function(){if(!q){q=true;s.initialized||H()}};if(typeof window=="undefined")A("No window found");
else if(typeof document=="undefined")A("No document found");else{p(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",y,false);if(p(window,"addEventListener"))window.addEventListener("load",y,false);else p(window,"attachEvent")?window.attachEvent("onload",y):A("Window does not have required addEventListener or attachEvent method");return s}}();
rangy.createModule("DomUtil",function(p,E){function F(e){for(var d=0;e=e.previousSibling;)d++;return d}function w(e,d){var i=[],q;for(q=e;q;q=q.parentNode)i.push(q);for(q=d;q;q=q.parentNode)if(s(i,q))return q;return null}function A(e,d,i){for(i=i?e:e.parentNode;i;){e=i.parentNode;if(e===d)return i;i=e}return null}function H(e){e=e.nodeType;return e==3||e==4||e==8}function G(e,d){var i=d.nextSibling,q=d.parentNode;i?q.insertBefore(e,i):q.appendChild(e);return e}function N(e){if(e.nodeType==9)return e;
else if(typeof e.ownerDocument!="undefined")return e.ownerDocument;else if(typeof e.document!="undefined")return e.document;else if(e.parentNode)return N(e.parentNode);else throw Error("getDocument: no document found for node");}function j(e){if(!e)return"[No node]";return H(e)?'"'+e.data+'"':e.nodeType==1?"<"+e.nodeName+(e.id?' id="'+e.id+'"':"")+">":e.nodeName}function l(e){this._next=this.root=e}function m(e,d){this.node=e;this.offset=d}function v(e){this.code=this[e];this.codeName=e;this.message=
"DOMException: "+this.codeName}var y=p.util;y.areHostMethods(document,["createDocumentFragment","createElement","createTextNode"])||E.fail("document missing a Node creation method");y.isHostMethod(document,"getElementsByTagName")||E.fail("document missing getElementsByTagName method");var t=document.createElement("div");y.areHostMethods(t,["insertBefore","appendChild","cloneNode"])||E.fail("Incomplete Element implementation");t=document.createTextNode("test");y.areHostMethods(t,["splitText","deleteData",
"insertData","appendData","cloneNode"])||E.fail("Incomplete Text Node implementation");var s=function(e,d){for(var i=e.length;i--;)if(e[i]===d)return true;return false};l.prototype={_current:null,hasNext:function(){return!!this._next},next:function(){var e=this._current=this._next,d;if(this._current)if(d=e.firstChild)this._next=d;else{for(d=null;e!==this.root&&!(d=e.nextSibling);)e=e.parentNode;this._next=d}return this._current},detach:function(){this._current=this._next=this.root=null}};m.prototype=
{equals:function(e){return this.node===e.node&this.offset==e.offset},inspect:function(){return"[DomPosition("+j(this.node)+":"+this.offset+")]"}};v.prototype={INDEX_SIZE_ERR:1,HIERARCHY_REQUEST_ERR:3,WRONG_DOCUMENT_ERR:4,NO_MODIFICATION_ALLOWED_ERR:7,NOT_FOUND_ERR:8,NOT_SUPPORTED_ERR:9,INVALID_STATE_ERR:11};v.prototype.toString=function(){return this.message};p.dom={arrayContains:s,getNodeIndex:F,getCommonAncestor:w,isAncestorOf:function(e,d,i){for(d=i?d:d.parentNode;d;)if(d===e)return true;else d=
d.parentNode;return false},getClosestAncestorIn:A,isCharacterDataNode:H,insertAfter:G,splitDataNode:function(e,d){var i;if(e.nodeType==3)i=e.splitText(d);else{i=e.cloneNode();i.deleteData(0,d);e.deleteData(0,e.length-d);G(i,e)}return i},getDocument:N,getWindow:function(e){e=N(e);if(typeof e.defaultView!="undefined")return e.defaultView;else if(typeof e.parentWindow!="undefined")return e.parentWindow;else throw Error("Cannot get a window object for node");},getBody:function(e){return y.isHostObject(e,
"body")?e.body:e.getElementsByTagName("body")[0]},comparePoints:function(e,d,i,q){var n;if(e==i)return d===q?0:d<q?-1:1;else if(n=A(i,e,true))return d<=F(n)?-1:1;else if(n=A(e,i,true))return F(n)<q?-1:1;else{d=w(e,i);e=e===d?d:A(e,d,true);i=i===d?d:A(i,d,true);if(e===i)throw Error("comparePoints got to case 4 and childA and childB are the same!");else{for(d=d.firstChild;d;){if(d===e)return-1;else if(d===i)return 1;d=d.nextSibling}throw Error("Should not be here!");}}},inspectNode:j,createIterator:function(e){return new l(e)},
DomPosition:m,DOMException:v}});
rangy.createModule("DomRange",function(p){function E(b,h){this.range=b;this.clonePartiallySelectedTextNodes=h;if(!b.collapsed){this.sc=b.startContainer;this.so=b.startOffset;this.ec=b.endContainer;this.eo=b.endOffset;var u=b.commonAncestorContainer;if(this.sc===this.ec&&a.isCharacterDataNode(this.sc)){this.isSingleCharacterDataNode=true;this._first=this._last=this._next=this.sc}else{this._first=this._next=this.sc===u&&!a.isCharacterDataNode(this.sc)?this.sc.childNodes[this.so]:a.getClosestAncestorIn(this.sc,
u,true);this._last=this.ec===u&&!a.isCharacterDataNode(this.ec)?this.ec.childNodes[this.eo-1]:a.getClosestAncestorIn(this.ec,u,true)}}}function F(b){this.code=this[b];this.codeName=b;this.message="RangeException: "+this.codeName}function w(b){return a.getDocument(b.startContainer)}function A(b,h,u){if(h=b._listeners[h])for(var z=0,I=h.length;z<I;++z)h[z].call(b,{target:b,args:u})}function H(b){return new g(b.parentNode,a.getNodeIndex(b))}function G(b){return new g(b.parentNode,a.getNodeIndex(b)+1)}
function N(b){return a.isCharacterDataNode(b)?b.length:b.childNodes?b.childNodes.length:0}function j(b,h,u){var z=b.nodeType==11?b.firstChild:b;if(a.isCharacterDataNode(h))u==h.length?a.insertAfter(b,h):h.parentNode.insertBefore(b,u==0?h:a.splitDataNode(h,u));else u>=h.childNodes.length?h.appendChild(b):h.insertBefore(b,h.childNodes[u]);return z}function l(b){for(var h,u,z=w(b.range).createDocumentFragment();u=b.next();){h=b.isPartiallySelectedSubtree();u=u.cloneNode(!h);if(h){h=b.getSubtreeIterator();
u.appendChild(l(h));h.detach(true)}if(u.nodeType==10)throw new k("HIERARCHY_REQUEST_ERR");z.appendChild(u)}return z}function m(b,h,u){var z,I;for(u=u||{stop:false};z=b.next();)if(b.isPartiallySelectedSubtree())if(h(z)===false){u.stop=true;return}else{z=b.getSubtreeIterator();m(z,h,u);z.detach(true);if(u.stop)return}else for(z=a.createIterator(z);I=z.next();)if(h(I)===false){u.stop=true;return}}function v(b){for(var h;b.next();)if(b.isPartiallySelectedSubtree()){h=b.getSubtreeIterator();v(h);h.detach(true)}else b.remove()}
function y(b){for(var h,u=w(b.range).createDocumentFragment(),z;h=b.next();){if(b.isPartiallySelectedSubtree()){h=h.cloneNode(false);z=b.getSubtreeIterator();h.appendChild(y(z));z.detach(true)}else b.remove();if(h.nodeType==10)throw new k("HIERARCHY_REQUEST_ERR");u.appendChild(h)}return u}function t(b,h,u){var z=!!(h&&h.length),I,T=!!u;if(z)I=RegExp("^("+h.join("|")+")$");var Y=[];m(new E(b,false),function(Z){if((!z||I.test(Z.nodeType))&&(!T||u(Z)))Y.push(Z)});return Y}function s(b){return"["+(typeof b.getName==
"undefined"?"Range":b.getName())+"("+a.inspectNode(b.startContainer)+":"+b.startOffset+", "+a.inspectNode(b.endContainer)+":"+b.endOffset+")]"}function e(b,h,u){this.nodes=t(b,h,u);this._next=this.nodes[0];this._pointer=0}function d(b,h){return b.nodeType!=3&&(a.isAncestorOf(b,h.startContainer,true)||a.isAncestorOf(b,h.endContainer,true))}function i(b){return function(h,u){for(var z,I=u?h:h.parentNode;I;){z=I.nodeType;if(a.arrayContains(b,z))return I;I=I.parentNode}return null}}function q(b){for(var h;h=
b.parentNode;)b=h;return b}function n(b,h){if(na(b,h))throw new F("INVALID_NODE_TYPE_ERR");}function r(b){if(!b.startContainer)throw new k("INVALID_STATE_ERR");}function x(b,h){if(!a.arrayContains(h,b.nodeType))throw new F("INVALID_NODE_TYPE_ERR");}function M(b,h){if(h<0||h>(a.isCharacterDataNode(b)?b.length:b.childNodes.length))throw new k("INDEX_SIZE_ERR");}function R(b,h){if(da(b,true)!==da(h,true))throw new k("WRONG_DOCUMENT_ERR");}function U(b){if(oa(b,true))throw new k("NO_MODIFICATION_ALLOWED_ERR");
}function V(b,h){if(!b)throw new k(h);}function K(b){if(!da(b.startContainer,true)||!da(b.endContainer,true)||!(b.startOffset<=(a.isCharacterDataNode(b.startContainer)?b.startContainer.length:b.startContainer.childNodes.length))||!(b.endOffset<=(a.isCharacterDataNode(b.endContainer)?b.endContainer.length:b.endContainer.childNodes.length)))throw Error("Range Range error: Range is no longer valid after DOM mutation ("+b.inspect()+")");}function W(b){b.START_TO_START=ea;b.START_TO_END=ha;b.END_TO_END=
pa;b.END_TO_START=ia;b.NODE_BEFORE=ja;b.NODE_AFTER=ka;b.NODE_BEFORE_AND_AFTER=la;b.NODE_INSIDE=fa}function B(b){W(b);W(b.prototype)}function X(b,h,u){function z(c,f){return function(o){r(this);x(o,D);x(q(o),O);o=(c?H:G)(o);(f?I:T)(this,o.node,o.offset)}}function I(c,f,o){var C=c.endContainer,L=c.endOffset;if(f!==c.startContainer||o!==this.startOffset){if(q(f)!=q(C)||a.comparePoints(f,o,C,L)==1){C=f;L=o}h(c,f,o,C,L)}}function T(c,f,o){var C=c.startContainer,L=c.startOffset;if(f!==c.endContainer||o!==
this.endOffset){if(q(f)!=q(C)||a.comparePoints(f,o,C,L)==-1){C=f;L=o}h(c,C,L,f,o)}}function Y(c,f,o){if(f!==c.startContainer||o!==this.startOffset||f!==c.endContainer||o!==this.endOffset)h(c,f,o,f,o)}function Z(c){return function(){r(this);K(this);var f=this.startContainer,o=this.startOffset,C=this.commonAncestorContainer,L=new E(this,true);if(f!==C){f=a.getClosestAncestorIn(f,C,true);o=G(f);f=o.node;o=o.offset}m(L,U);L.reset();C=c(L);L.detach();h(this,f,o,f,o);return C}}b.prototype={attachListener:function(c,
f){this._listeners[c].push(f)},setStart:function(c,f){r(this);n(c,true);M(c,f);I(this,c,f)},setEnd:function(c,f){r(this);n(c,true);M(c,f);T(this,c,f)},setStartBefore:z(true,true),setStartAfter:z(false,true),setEndBefore:z(true,false),setEndAfter:z(false,false),collapse:function(c){r(this);K(this);c?h(this,this.startContainer,this.startOffset,this.startContainer,this.startOffset):h(this,this.endContainer,this.endOffset,this.endContainer,this.endOffset)},selectNodeContents:function(c){r(this);n(c,true);
h(this,c,0,c,N(c))},selectNode:function(c){r(this);n(c,false);x(c,D);var f=H(c);c=G(c);h(this,f.node,f.offset,c.node,c.offset)},compareBoundaryPoints:function(c,f){r(this);K(this);R(this.startContainer,f.startContainer);var o=c==ia||c==ea?"start":"end",C=c==ha||c==ea?"start":"end";return a.comparePoints(this[o+"Container"],this[o+"Offset"],f[C+"Container"],f[C+"Offset"])},insertNode:function(c){r(this);K(this);x(c,P);U(this.startContainer);if(a.isAncestorOf(c,this.startContainer,true))throw new k("HIERARCHY_REQUEST_ERR");
this.setStartBefore(j(c,this.startContainer,this.startOffset))},cloneContents:function(){r(this);K(this);var c,f;if(this.collapsed)return w(this).createDocumentFragment();else{if(this.startContainer===this.endContainer&&a.isCharacterDataNode(this.startContainer)){c=this.startContainer.cloneNode(true);c.data=c.data.slice(this.startOffset,this.endOffset);f=w(this).createDocumentFragment();f.appendChild(c);return f}else{f=new E(this,true);c=l(f);f.detach()}return c}},extractContents:Z(y),deleteContents:Z(v),
surroundContents:function(c){r(this);K(this);U(this.startContainer);U(this.endContainer);x(c,aa);var f=new E(this,true),o=f._first&&d(f._first,this)||f._last&&d(f._last,this);f.detach();if(o)throw new F("BAD_BOUNDARYPOINTS_ERR");f=this.extractContents();if(c.hasChildNodes())for(;c.lastChild;)c.removeChild(c.lastChild);j(c,this.startContainer,this.startOffset);c.appendChild(f);this.selectNode(c)},cloneRange:function(){r(this);K(this);for(var c=new J(w(this)),f=ga.length,o;f--;){o=ga[f];c[o]=this[o]}return c},
detach:function(){u(this)},toString:function(){r(this);K(this);var c=this.startContainer;if(c===this.endContainer&&a.isCharacterDataNode(c))return c.nodeType==3||c.nodeType==4?c.data.slice(this.startOffset,this.endOffset):"";else{var f=[];c=new E(this,true);m(c,function(o){if(o.nodeType==3||o.nodeType==4)f.push(o.data)});c.detach();return f.join("")}},compareNode:function(c){r(this);K(this);var f=c.parentNode,o=a.getNodeIndex(c);if(!f)throw new k("NOT_FOUND_ERR");c=this.comparePoint(f,o);f=this.comparePoint(f,
o+1);return c<0?f>0?la:ja:f>0?ka:fa},comparePoint:function(c,f){r(this);K(this);V(c,"HIERARCHY_REQUEST_ERR");R(c,this.startContainer);if(a.comparePoints(c,f,this.startContainer,this.startOffset)<0)return-1;else if(a.comparePoints(c,f,this.endContainer,this.endOffset)>0)return 1;return 0},createContextualFragment:function(c){r(this);var f=w(this),o=f.createElement("div");o.innerHTML=c;for(c=f.createDocumentFragment();f=o.firstChild;)c.appendChild(f);return c},intersectsNode:function(c){r(this);K(this);
V(c,"NOT_FOUND_ERR");if(a.getDocument(c)!==w(this))return false;var f=c.parentNode,o=a.getNodeIndex(c);V(f,"NOT_FOUND_ERR");c=a.comparePoints(f,o,this.startContainer,this.startOffset);f=a.comparePoints(f,o+1,this.endContainer,this.endOffset);return!(c<0&&f<0||c>0&&f>0)},isPointInRange:function(c,f){r(this);K(this);V(c,"HIERARCHY_REQUEST_ERR");R(c,this.startContainer);return a.comparePoints(c,f,this.startContainer,this.startOffset)>=0&&a.comparePoints(c,f,this.endContainer,this.endOffset)<=0},intersectsRange:function(c){r(this);
K(this);if(w(c)!=w(this))throw new k("WRONG_DOCUMENT_ERR");return a.comparePoints(this.startContainer,this.startOffset,c.endContainer,c.endOffset)<0&&a.comparePoints(this.endContainer,this.endOffset,c.startContainer,c.startOffset)>0},containsNode:function(c,f){return f?this.intersectsNode(c):this.compareNode(c)==fa},containsNodeContents:function(c){return this.comparePoint(c,0)>=0&&this.comparePoint(c,N(c))<=0},splitBoundaries:function(){r(this);K(this);var c=this.startContainer,f=this.startOffset,
o=this.endContainer,C=this.endOffset,L=c===o;a.isCharacterDataNode(o)&&C<o.length&&a.splitDataNode(o,C);if(a.isCharacterDataNode(c)&&f>0){c=a.splitDataNode(c,f);if(L){C-=f;o=c}f=0}h(this,c,f,o,C)},normalizeBoundaries:function(){r(this);K(this);var c=this.startContainer,f=this.startOffset,o=this.endContainer,C=this.endOffset,L=function(S){var Q=S.nextSibling;if(Q&&Q.nodeType==S.nodeType){o=S;C=S.length;S.appendData(Q.data);Q.parentNode.removeChild(Q)}},ma=function(S){var Q=S.previousSibling;if(Q&&
Q.nodeType==S.nodeType){c=S;f=Q.length;S.insertData(0,Q.data);Q.parentNode.removeChild(Q);if(c==o){C+=f;o=c}}},ba=true;if(a.isCharacterDataNode(o))o.length==C&&L(o);else{if(C>0)(ba=o.childNodes[C-1])&&a.isCharacterDataNode(ba)&&L(ba);ba=!this.collapsed}if(ba)if(a.isCharacterDataNode(c))f==0&&ma(c);else{if(f<c.childNodes.length)(L=c.childNodes[f])&&a.isCharacterDataNode(L)&&ma(L)}else{c=o;f=C}h(this,c,f,o,C)},createNodeIterator:function(c,f){r(this);K(this);return new e(this,c,f)},getNodes:function(c,
f){r(this);K(this);return t(this,c,f)},collapseToPoint:function(c,f){r(this);K(this);n(c,true);M(c,f);Y(this,c,f)},collapseBefore:function(c){r(this);this.setEndBefore(c);this.collapse(false)},collapseAfter:function(c){r(this);this.setStartAfter(c);this.collapse(true)},getName:function(){return"DomRange"},inspect:function(){return s(this)}};B(b)}function ca(b){b.collapsed=b.startContainer===b.endContainer&&b.startOffset===b.endOffset;b.commonAncestorContainer=b.collapsed?b.startContainer:a.getCommonAncestor(b.startContainer,
b.endContainer)}function $(b,h,u,z,I){var T=b.startContainer!==h||b.startOffset!==u,Y=b.endContainer!==z||b.endOffset!==I;b.startContainer=h;b.startOffset=u;b.endContainer=z;b.endOffset=I;ca(b);A(b,"boundarychange",{startMoved:T,endMoved:Y})}function J(b){this.startContainer=b;this.startOffset=0;this.endContainer=b;this.endOffset=0;this._listeners={boundarychange:[],detach:[]};ca(this)}p.requireModules(["DomUtil"]);var a=p.dom,g=a.DomPosition,k=a.DOMException;E.prototype={_current:null,_next:null,
_first:null,_last:null,isSingleCharacterDataNode:false,reset:function(){this._current=null;this._next=this._first},hasNext:function(){return!!this._next},next:function(){var b=this._current=this._next;if(b){this._next=b!==this._last?b.nextSibling:null;if(a.isCharacterDataNode(b)&&this.clonePartiallySelectedTextNodes){if(b===this.ec)(b=b.cloneNode(true)).deleteData(this.eo,b.length-this.eo);if(this._current===this.sc)(b=b.cloneNode(true)).deleteData(0,this.so)}}return b},remove:function(){var b=this._current,
h,u;if(a.isCharacterDataNode(b)&&(b===this.sc||b===this.ec)){h=b===this.sc?this.so:0;u=b===this.ec?this.eo:b.length;h!=u&&b.deleteData(h,u-h)}else b.parentNode&&b.parentNode.removeChild(b)},isPartiallySelectedSubtree:function(){return d(this._current,this.range)},getSubtreeIterator:function(){var b;if(this.isSingleCharacterDataNode){b=this.range.cloneRange();b.collapse()}else{b=new J(w(this.range));var h=this._current,u=h,z=0,I=h,T=N(h);if(a.isAncestorOf(h,this.sc,true)){u=this.sc;z=this.so}if(a.isAncestorOf(h,
this.ec,true)){I=this.ec;T=this.eo}$(b,u,z,I,T)}return new E(b,this.clonePartiallySelectedTextNodes)},detach:function(b){b&&this.range.detach();this.range=this._current=this._next=this._first=this._last=this.sc=this.so=this.ec=this.eo=null}};F.prototype={BAD_BOUNDARYPOINTS_ERR:1,INVALID_NODE_TYPE_ERR:2};F.prototype.toString=function(){return this.message};e.prototype={_current:null,hasNext:function(){return!!this._next},next:function(){this._current=this._next;this._next=this.nodes[++this._pointer];
return this._current},detach:function(){this._current=this._next=this.nodes=null}};var D=[1,3,4,5,7,8,10],O=[2,9,11],P=[1,3,4,5,7,8,10,11],aa=[1,3,4,5,7,8],da=i([9,11]),oa=i([5,6,10,12]),na=i([6,10,12]),ga=["startContainer","startOffset","endContainer","endOffset","collapsed","commonAncestorContainer"],ea=0,ha=1,pa=2,ia=3,ja=0,ka=1,la=2,fa=3;X(J,$,function(b){r(b);b.startContainer=b.startOffset=b.endContainer=b.endOffset=null;b.collapsed=b.commonAncestorContainer=null;A(b,"detach",null);b._listeners=
null});J.fromRange=function(b){var h=new J(w(b));$(h,b.startContainer,b.startOffset,b.endContainer,b.endOffset);return h};J.rangeProperties=ga;J.RangeIterator=E;J.DOMException=k;J.RangeException=F;J.copyComparisonConstants=B;J.createPrototypeRange=X;J.inspect=s;J.getRangeDocument=w;J.rangesEqual=function(b,h){return b.startContainer===h.startContainer&&b.startOffset===h.startOffset&&b.endContainer===h.endContainer&&b.endOffset===h.endOffset};J.getEndOffset=N;p.DomRange=J});
rangy.createModule("WrappedRange",function(p){function E(j,l,m,v){var y=j.duplicate();y.collapse(m);var t=y.parentElement();A.isAncestorOf(l,t,true)||(t=l);if(!t.canHaveHTML)return new H(t.parentNode,A.getNodeIndex(t));l=A.getDocument(t).createElement("span");var s,e=m?"StartToStart":"StartToEnd";do{t.insertBefore(l,l.previousSibling);y.moveToElementText(l)}while((s=y.compareEndPoints(e,j))>0&&l.previousSibling);e=l.nextSibling;if(s==-1&&e){y.setEndPoint(m?"EndToStart":"EndToEnd",j);if(/[\r\n]/.test(e.data)){t=
y.duplicate();m=t.text.replace(/\r\n/g,"\r").length;for(m=t.moveStart("character",m);t.compareEndPoints("StartToEnd",t)==-1;){m++;t.moveStart("character",1)}}else m=y.text.length;t=new H(e,m)}else{e=(v||!m)&&l.previousSibling;t=(m=(v||m)&&l.nextSibling)&&A.isCharacterDataNode(m)?new H(m,0):e&&A.isCharacterDataNode(e)?new H(e,e.length):new H(t,A.getNodeIndex(l))}l.parentNode.removeChild(l);return t}function F(j,l){var m,v,y=j.offset,t=A.getDocument(j.node),s=t.body.createTextRange(),e=A.isCharacterDataNode(j.node);
if(e){m=j.node;v=m.parentNode}else{m=j.node.childNodes;m=y<m.length?m[y]:null;v=j.node}t=t.createElement("span");t.innerHTML="&#ffef;";m?v.insertBefore(t,m):v.appendChild(t);s.moveToElementText(t);s.collapse(!l);v.removeChild(t);if(e)s[l?"moveStart":"moveEnd"]("character",y);return s}p.requireModules(["DomUtil","DomRange"]);var w,A=p.dom,H=A.DomPosition,G=p.DomRange;if(p.features.implementsDomRange)(function(){function j(d){for(var i=m.length,q;i--;){q=m[i];d[q]=d.nativeRange[q]}}var l,m=G.rangeProperties,
v,y;w=function(d){if(!d)throw Error("Range must be specified");this.nativeRange=d;j(this)};G.createPrototypeRange(w,function(d,i,q,n,r){var x=d.startContainer!==i||d.startOffset!=q;(d.endContainer!==n||d.endOffset!=r)&&d.setEnd(n,r);x&&d.setStart(i,q)},function(d){d.nativeRange.detach();d.detached=true;for(var i=m.length,q;i--;){q=m[i];d[q]=null}});l=w.prototype;l.selectNode=function(d){this.nativeRange.selectNode(d);j(this)};l.deleteContents=function(){this.nativeRange.deleteContents();j(this)};
l.extractContents=function(){var d=this.nativeRange.extractContents();j(this);return d};l.cloneContents=function(){return this.nativeRange.cloneContents()};l.surroundContents=function(d){this.nativeRange.surroundContents(d);j(this)};l.collapse=function(d){this.nativeRange.collapse(d);j(this)};l.cloneRange=function(){return new w(this.nativeRange.cloneRange())};l.refresh=function(){j(this)};l.toString=function(){return this.nativeRange.toString()};var t=document.createTextNode("test");A.getBody(document).appendChild(t);
var s=document.createRange();s.setStart(t,0);s.setEnd(t,0);try{s.setStart(t,1);v=true;l.setStart=function(d,i){this.nativeRange.setStart(d,i);j(this)};l.setEnd=function(d,i){this.nativeRange.setEnd(d,i);j(this)};y=function(d){return function(i){this.nativeRange[d](i);j(this)}}}catch(e){v=false;l.setStart=function(d,i){try{this.nativeRange.setStart(d,i)}catch(q){this.nativeRange.setEnd(d,i);this.nativeRange.setStart(d,i)}j(this)};l.setEnd=function(d,i){try{this.nativeRange.setEnd(d,i)}catch(q){this.nativeRange.setStart(d,
i);this.nativeRange.setEnd(d,i)}j(this)};y=function(d,i){return function(q){try{this.nativeRange[d](q)}catch(n){this.nativeRange[i](q);this.nativeRange[d](q)}j(this)}}}l.setStartBefore=y("setStartBefore","setEndBefore");l.setStartAfter=y("setStartAfter","setEndAfter");l.setEndBefore=y("setEndBefore","setStartBefore");l.setEndAfter=y("setEndAfter","setStartAfter");s.selectNodeContents(t);l.selectNodeContents=s.startContainer==t&&s.endContainer==t&&s.startOffset==0&&s.endOffset==t.length?function(d){this.nativeRange.selectNodeContents(d);
j(this)}:function(d){this.setStart(d,0);this.setEnd(d,G.getEndOffset(d))};s.selectNodeContents(t);s.setEnd(t,3);v=document.createRange();v.selectNodeContents(t);v.setEnd(t,4);v.setStart(t,2);l.compareBoundaryPoints=s.compareBoundaryPoints(s.START_TO_END,v)==-1&&s.compareBoundaryPoints(s.END_TO_START,v)==1?function(d,i){i=i.nativeRange||i;if(d==i.START_TO_END)d=i.END_TO_START;else if(d==i.END_TO_START)d=i.START_TO_END;return this.nativeRange.compareBoundaryPoints(d,i)}:function(d,i){return this.nativeRange.compareBoundaryPoints(d,
i.nativeRange||i)};A.getBody(document).removeChild(t);s.detach();v.detach()})();else if(p.features.implementsTextRange){w=function(j){this.textRange=j;this.refresh()};w.prototype=new G(document);w.prototype.refresh=function(){var j,l;l=this.textRange;j=l.parentElement();var m=l.duplicate(),v=m.getBookmark();m.collapse(true);l=m.parentElement();m.moveToBookmark(v);m.collapse(false);m=m.parentElement();l=l==m?l:A.getCommonAncestor(l,m);l=l==j?l:A.getCommonAncestor(j,l);if(this.textRange.compareEndPoints("StartToEnd",
this.textRange)==0)l=j=E(this.textRange,l,true,true);else{j=E(this.textRange,l,true,false);l=E(this.textRange,l,false,false)}this.setStart(j.node,j.offset);this.setEnd(l.node,l.offset)};w.rangeToTextRange=function(j){if(j.collapsed)return F(new H(j.startContainer,j.startOffset),true,true);else{var l=F(new H(j.startContainer,j.startOffset),true,false),m=F(new H(j.endContainer,j.endOffset),false,false);j=A.getDocument(j.startContainer).body.createTextRange();j.setEndPoint("StartToStart",l);j.setEndPoint("EndToEnd",
m);return j}};G.copyComparisonConstants(w);var N=function(){return this}();if(typeof N.Range=="undefined")N.Range=w}w.prototype.getName=function(){return"WrappedRange"};p.WrappedRange=w;p.createNativeRange=function(j){j=j||document;if(p.features.implementsDomRange)return j.createRange();else if(p.features.implementsTextRange)return j.body.createTextRange()};p.createRange=function(j){j=j||document;return new w(p.createNativeRange(j))};p.createRangyRange=function(j){j=j||document;return new G(j)};p.addCreateMissingNativeApiListener(function(j){j=
j.document;if(typeof j.createRange=="undefined")j.createRange=function(){return p.createRange(this)};j=j=null})});
rangy.createModule("WrappedSelection",function(p,E){function F(a,g,k){var D=k?"end":"start";k=k?"start":"end";a.anchorNode=g[D+"Container"];a.anchorOffset=g[D+"Offset"];a.focusNode=g[k+"Container"];a.focusOffset=g[k+"Offset"]}function w(a){a.anchorNode=a.focusNode=null;a.anchorOffset=a.focusOffset=0;a.rangeCount=0;a.isCollapsed=true;a._ranges.length=0}function A(a){var g;if(a instanceof y){g=a._selectionNativeRange;if(!g){g=p.createNativeRange(m.getDocument(a.startContainer));g.setEnd(a.endContainer,
a.endOffset);g.setStart(a.startContainer,a.startOffset);a._selectionNativeRange=g;a.attachListener("detach",function(){this._selectionNativeRange=null})}}else if(a instanceof t)g=a.nativeRange;else if(window.Range&&a instanceof Range)g=a;return g}function H(a){a=a.getNodes();if(a.length!=1||a[0].nodeType!=1)throw Error("getSingleElementFromRange: range did not consist of a single element");return a[0]}function G(a){a._ranges.length=0;if(a.nativeSelection.type=="None")w(a);else{var g=a.nativeSelection.createRange();
a.rangeCount=g.length;for(var k,D=m.getDocument(g.item(0)),O=0;O<a.rangeCount;++O){k=p.createRange(D);k.selectNode(g.item(O));a._ranges.push(k)}a.isCollapsed=a.rangeCount==1&&a._ranges[0].collapsed;F(a,a._ranges[a.rangeCount-1],false)}}function N(a){this.nativeSelection=a;this._ranges=[];this.refresh()}function j(a,g){if(a.anchorNode&&m.getDocument(a.anchorNode)!==m.getDocument(g))throw new s("WRONG_DOCUMENT_ERR");}function l(a){var g=[],k=new e(a.anchorNode,a.anchorOffset),D=new e(a.focusNode,a.focusOffset),
O=typeof a.getName=="function"?a.getName():"Selection";if(typeof a.rangeCount!="undefined")for(var P=0,aa=a.rangeCount;P<aa;++P)g[P]=y.inspect(a.getRangeAt(P));return"["+O+"(Ranges: "+g.join(", ")+")(anchor: "+k.inspect()+", focus: "+D.inspect()+"]"}p.requireModules(["DomUtil","DomRange","WrappedRange"]);p.config.checkSelectionRanges=true;var m=p.dom,v=p.util,y=p.DomRange,t=p.WrappedRange,s=m.DOMException,e=m.DomPosition,d,i;if(p.util.isHostMethod(window,"getSelection"))d=function(a){return(a||window).getSelection()};
else if(p.util.isHostObject(document,"selection"))d=function(a){return(a||window).document.selection};else E.fail("No means of obtaining a selection object");p.getNativeSelection=d;var q=d(),n=p.createNativeRange(document),r=m.getBody(document),x=v.areHostObjects(q,v.areHostProperties(q,["anchorOffset","focusOffset"]));p.features.selectionHasAnchorAndFocus=x;var M=v.isHostMethod(q,"extend");p.features.selectionHasExtend=M;var R=typeof q.rangeCount=="number";p.features.selectionHasRangeCount=R;var U=
false,V=true;v.areHostMethods(q,["addRange","getRangeAt","removeAllRanges"])&&typeof q.rangeCount=="number"&&p.features.implementsDomRange&&function(){var a=r.appendChild(document.createTextNode("One")),g=r.appendChild(document.createTextNode("Two")),k=p.createNativeRange(document);k.selectNodeContents(a);var D=p.createNativeRange(document);D.selectNodeContents(g);q.removeAllRanges();q.addRange(k);q.addRange(D);U=q.rangeCount==2;q.removeAllRanges();a.parentNode.removeChild(a);g.parentNode.removeChild(g);
a=document.createElement("p");a.contentEditable=false;g=a.appendChild(document.createTextNode("test"));r.appendChild(a);k=p.createRange();k.collapseToPoint(g,1);q.addRange(k.nativeRange);V=q.rangeCount==1;q.removeAllRanges();r.removeChild(a)}();p.features.selectionSupportsMultipleRanges=U;p.features.collapsedNonEditableSelectionsSupported=V;var K=v.isHostProperty(q,"type"),W=false,B;if(r&&v.isHostMethod(r,"createControlRange")){B=r.createControlRange();if(v.areHostProperties(B,["item","add"]))W=true}p.features.implementsControlRange=
W;i=x?function(a){return a.anchorNode===a.focusNode&&a.anchorOffset===a.focusOffset}:function(a){return a.rangeCount?a.getRangeAt(a.rangeCount-1).collapsed:false};var X;if(v.isHostMethod(q,"getRangeAt"))X=function(a,g){try{return a.getRangeAt(g)}catch(k){return null}};else if(x)X=function(a){var g=m.getDocument(a.anchorNode);g=p.createRange(g);g.setStart(a.anchorNode,a.anchorOffset);g.setEnd(a.focusNode,a.focusOffset);if(g.collapsed!==this.isCollapsed){g.setStart(a.focusNode,a.focusOffset);g.setEnd(a.anchorNode,
a.anchorOffset)}return g};p.getSelection=function(a){a=a||window;var g=a._rangySelection;if(g){g.nativeSelection=d(a);g.refresh()}else{g=new N(d(a));a._rangySelection=g}return g};B=N.prototype;if(x&&v.areHostMethods(q,["removeAllRanges","addRange"])){B.removeAllRanges=function(){this.nativeSelection.removeAllRanges();w(this)};var ca=function(a,g){var k=y.getRangeDocument(g);k=p.createRange(k);k.collapseToPoint(g.endContainer,g.endOffset);a.nativeSelection.addRange(A(k));a.nativeSelection.extend(g.startContainer,
g.startOffset);a.refresh()};B.addRange=R?function(a,g){if(g&&M)ca(this,a);else{var k;if(U)k=this.rangeCount;else{this.removeAllRanges();k=0}this.nativeSelection.addRange(A(a));this.rangeCount=this.nativeSelection.rangeCount;if(this.rangeCount==k+1){if(p.config.checkSelectionRanges)if((k=X(this.nativeSelection,this.rangeCount-1))&&!y.rangesEqual(k,a))a=k;this._ranges[this.rangeCount-1]=a;F(this,a,J(this.nativeSelection));this.isCollapsed=i(this)}else this.refresh()}}:function(a,g){if(g&&M)ca(this,
a);else{this.nativeSelection.addRange(A(a));this.refresh()}};B.setRanges=function(a){this.removeAllRanges();for(var g=0,k=a.length;g<k;++g)this.addRange(a[g])}}else if(v.isHostMethod(q,"empty")&&v.isHostMethod(n,"select")&&K&&W){B.removeAllRanges=function(){this.nativeSelection.empty();w(this)};B.addRange=function(a){if(this.nativeSelection.type=="Control"){var g=this.nativeSelection.createRange();a=H(a);var k=m.getDocument(g.item(0));k=m.getBody(k).createControlRange();for(var D=0,O=g.length;D<O;++D)k.add(g.item(D));
k.add(a);k.select();G(this)}else{t.rangeToTextRange(a).select();this._ranges[0]=a;this.rangeCount=1;this.isCollapsed=this._ranges[0].collapsed;F(this,a,false)}};B.setRanges=function(a){this.removeAllRanges();var g=a.length;if(g>1){var k=m.getDocument(a[0].startContainer);k=m.getBody(k).createControlRange();for(var D=0;D<g;++D)k.add(H(a[D]));k.select();G(this)}else g&&this.addRange(a[0])}}else{E.fail("No means of selecting a Range or TextRange was found");return false}B.getRangeAt=function(a){if(a<
0||a>=this.rangeCount)throw new s("INDEX_SIZE_ERR");else return this._ranges[a]};if(v.isHostMethod(q,"getRangeAt")&&typeof q.rangeCount=="number")B.refresh=function(){if(this._ranges.length=this.rangeCount=this.nativeSelection.rangeCount){for(var a=0,g=this.rangeCount;a<g;++a)this._ranges[a]=new p.WrappedRange(this.nativeSelection.getRangeAt(a));F(this,this._ranges[this.rangeCount-1],J(this.nativeSelection));this.isCollapsed=i(this)}else w(this)};else if(x&&typeof q.isCollapsed=="boolean"&&typeof n.collapsed==
"boolean"&&p.features.implementsDomRange)B.refresh=function(){var a;a=this.nativeSelection;if(a.anchorNode){a=X(a,0);this._ranges=[a];this.rangeCount=1;a=this.nativeSelection;this.anchorNode=a.anchorNode;this.anchorOffset=a.anchorOffset;this.focusNode=a.focusNode;this.focusOffset=a.focusOffset;this.isCollapsed=i(this)}else w(this)};else if(v.isHostMethod(q,"createRange")&&p.features.implementsTextRange)B.refresh=function(){var a=this.nativeSelection.createRange();if(this.nativeSelection.type=="Control")G(this);
else if(a&&typeof a.text!="undefined"){a=new t(a);this._ranges=[a];F(this,a,false);this.rangeCount=1;this.isCollapsed=a.collapsed}else w(this)};else{E.fail("No means of obtaining a Range or TextRange from the user's selection was found");return false}var $=function(a,g){var k=a.getAllRanges(),D=false;a.removeAllRanges();for(var O=0,P=k.length;O<P;++O)if(D||g!==k[O])a.addRange(k[O]);else D=true;a.rangeCount||w(a)};B.removeRange=K&&W?function(a){if(this.nativeSelection.type=="Control"){var g=this.nativeSelection.createRange();
a=H(a);var k=m.getDocument(g.item(0));k=m.getBody(k).createControlRange();for(var D,O=false,P=0,aa=g.length;P<aa;++P){D=g.item(P);if(D!==a||O)k.add(g.item(P));else O=true}k.select();G(this)}else $(this,a)}:function(a){$(this,a)};var J;if(x&&p.features.implementsDomRange){J=function(a){var g=false;if(a.anchorNode)g=m.comparePoints(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset)==1;return g};B.isBackwards=function(){return J(this)}}else J=B.isBackwards=function(){return false};B.toString=function(){for(var a=
[],g=0,k=this.rangeCount;g<k;++g)a[g]=""+this._ranges[g];return a.join("")};B.collapse=function(a,g){j(this,a);var k=p.createRange(m.getDocument(a));k.collapseToPoint(a,g);this.removeAllRanges();this.addRange(k);this.isCollapsed=true};B.collapseToStart=function(){if(this.rangeCount){var a=this._ranges[0];this.collapse(a.startContainer,a.startOffset)}else throw new s("INVALID_STATE_ERR");};B.collapseToEnd=function(){if(this.rangeCount){var a=this._ranges[this.rangeCount-1];this.collapse(a.endContainer,
a.endOffset)}else throw new s("INVALID_STATE_ERR");};B.selectAllChildren=function(a){j(this,a);var g=p.createRange(m.getDocument(a));g.selectNodeContents(a);this.removeAllRanges();this.addRange(g)};B.deleteFromDocument=function(){if(this.rangeCount){var a=this.getAllRanges();this.removeAllRanges();for(var g=0,k=a.length;g<k;++g)a[g].deleteContents();this.addRange(a[k-1])}};B.getAllRanges=function(){return this._ranges.slice(0)};B.setSingleRange=function(a){this.setRanges([a])};B.containsNode=function(a,
g){for(var k=0,D=this._ranges.length;k<D;++k)if(this._ranges[k].containsNode(a,g))return true;return false};B.getName=function(){return"WrappedSelection"};B.inspect=function(){return l(this)};B.detach=function(){if(this.anchorNode)m.getWindow(this.anchorNode)._rangySelection=null};N.inspect=l;p.Selection=N;p.addCreateMissingNativeApiListener(function(a){if(typeof a.getSelection=="undefined")a.getSelection=function(){return p.getSelection(this)};a=null})});